# Using Historical Data to Predict Batting Success: Step 5 - OPS Modelling

Authored by: Donna J. Harris (994042890)

Email: harr2890@mylaurier.ca

For: CP640 Machine Learning (S22) with Professor Elham Harirpoush

## Notebook Series

Just a word about the presentation of this project code.

The code is organized into a series of locally executed Jupyter notebooks, organized by step and needing to be executed in sequence. This is `harr2890_project_step5_ops_modelling`, the fifth of XXXXX notebooks.  TODO

## *Step 5 - Exploration and Modelling for an OPS Approach*

word words word TODO


## Environment Setup

Import and establish environment for our work, including showing all dataframe column values.

In [1]:
import pandas as pd

pd.set_option('display.max_columns', None)

### Pre-Conditions

Steps 1 and 4 must be run completely before running this notebook.

The `data` folder must exist with the following prepared data files:
- `./data/step4_alldata.csv`
- `./data/step4_pre_2000.csv`
- `./data/step4_from_2000.csv`

##  Loading Prepared Data Files

In [2]:
alldata_csv = "./data/step4_alldata.csv"
alldata = pd.read_csv(alldata_csv)
alldata

ID             Player     PA    AB     R     H   2B   3B   HR  \
0     willeed01         Ed Willett    704   649    56   129   25   10    5   
1     daussho01        Hooks Dauss   1324  1125   107   212   41   15    6   
2     coopewi01      Wilbur Cooper   1320  1232   111   295   34   18    6   
3     mamaual01          Al Mamaux    466   421    39    77   12    2    1   
4      ruthba01          Babe Ruth  10624  8400  2173  2872  506  137  714   
...         ...                ...    ...   ...   ...   ...  ...  ...  ...   
2394  perezhe01       Hernan Perez   1846  1745   188   436   74   11   45   
2395  gomesya01          Yan Gomes   3274  3006   369   742  158    8  117   
2396  simmoan01  Andrelton Simmons   4731  4366   493  1156  200   23   70   
2397  mercejo03       Jordy Mercer   3416  3104   327   796  173   15   66   
2398  grandya01    Yasmani Grandal   3861  3233   461   777  152    7  172   

       RBI    BB    SO  HBP  SH  SF  Number of Seasons  Career AVG  \
0       68    25   174    6  24   0                 10    0.198767   
1      112   145   288    8  41   0                 15    0.188444   
2      103    46   139    4  35   0                 15    0.239448   
3       31    27    90    3  12   0                 12    0.182898   
4     2215  2063  1331   45  45   0                 22    0.341905   
...    ...   ...   ...  ...  ..  ..                ...         ...   
2394   180    76   397    1  12  12                 10    0.249857   
2395   416   185   794   50   2  31                 10    0.246840   
2396   437   297   448   26  13  29                 10    0.264773   
2397   308   246   589   27  22  17                 10    0.256443   
2398   505   574   913   20   3  31                 10    0.240334   

      Career SLG  Career OBP  Career OPS    OPS Y1    OPS Y2    OPS Y3  \
0       0.291217    0.235294    0.526511  0.000000  0.219780  0.367510   
1       0.267556    0.285603    0.553158  1.000000  0.560802  0.578379   
2       0.310877    0.269111    0.579987  0.368132  0.219780  0.462535   
3       0.228029    0.237251    0.465279  0.000000  0.550000  0.363387   
4       0.689762    0.473925    1.163687  0.500000  0.952325  0.730611   
...          ...         ...         ...       ...       ...       ...   
2394    0.382235    0.279716    0.661951  1.000000  0.444664  0.533333   
2395    0.421490    0.298594    0.720084  0.630983  0.825949  0.784906   
2396    0.369217    0.313480    0.682697  0.750827  0.691599  0.617196   
2397    0.385631    0.314968    0.700599  0.635674  0.771547  0.692806   
2398    0.451284    0.355365    0.806649  0.862555  0.692761  0.727844   

        OPS Y4    OPS Y5    OPS Y6    OPS Y7    OPS Y8    OPS Y9   OPS Y10  \
0     0.496266  0.379030  0.774655  0.456006  0.692935  0.621154  0.533333   
1     0.470550  0.731898  0.400920  0.559740  0.379742  0.542872  0.634387   
2     0.260180  0.455696  0.519551  0.591622  0.679654  0.537423  0.611333   
3     0.473844  0.475806  0.000000  0.479365  0.464706  0.431818  0.991071   
4     0.856730  0.967903  1.114268  1.379841  1.355617  1.103689  1.313417   
...        ...       ...       ...       ...       ...       ...       ...   
2394  0.583502  0.730326  0.703826  0.676495  0.641605  0.333333  0.195489   
2395  0.658537  0.527451  0.707728  0.761775  0.704177  0.787218  0.722537   
2396  0.659624  0.689723  0.751810  0.754196  0.673284  0.702389  0.557754   
2397  0.613224  0.701352  0.732539  0.695653  0.747463  0.472727  0.671493   
2398  0.755758  0.816092  0.766596  0.815330  0.847583  0.772876  0.939499   

        AVG Y1    AVG Y2    AVG Y3    AVG Y4    AVG Y5    AVG Y6    AVG Y7  \
0     0.000000  0.076923  0.164179  0.190909  0.134146  0.268293  0.165217   
1     0.250000  0.177215  0.216495  0.145631  0.222222  0.126437  0.181818   
2     0.153846  0.076923  0.206522  0.114754  0.215190  0.203883  0.242105   
3     0.000000  0.250000  0.163043  0.190909  0.225806  0.000000  0.174603   
4     0.200000  0.3

In [3]:
pre_2000_csv = "./data/step4_pre_2000.csv"
pre_2000 = pd.read_csv(pre_2000_csv)
pre_2000

ID           Player     PA    AB     R     H   2B   3B   HR  \
0     willeed01       Ed Willett    704   649    56   129   25   10    5   
1     daussho01      Hooks Dauss   1324  1125   107   212   41   15    6   
2     coopewi01    Wilbur Cooper   1320  1232   111   295   34   18    6   
3     mamaual01        Al Mamaux    466   421    39    77   12    2    1   
4      ruthba01        Babe Ruth  10624  8400  2173  2872  506  137  714   
...         ...              ...    ...   ...   ...   ...  ...  ...  ...   
1991  berkmla01    Lance Berkman   7814  6491  1145  1905  422   30  366   
1992  burnea.01     A.J. Burnett    575   493    20    56    8    3    4   
1993  garcifr03    Freddy Garcia     99    77     1    12    2    0    0   
1994  weaveje01      Jeff Weaver    239   208    13    43    6    1    0   
1995  hernara02  Ramon Hernandez   5701  5105   580  1345  262    8  169   

       RBI    BB    SO  HBP  SH  SF  Number of Seasons  Career AVG  \
0       68    25   174    6  24   0                 10    0.198767   
1      112   145   288    8  41   0                 15    0.188444   
2      103    46   139    4  35   0                 15    0.239448   
3       31    27    90    3  12   0                 12    0.182898   
4     2215  2063  1331   45  45   0                 22    0.341905   
...    ...   ...   ...  ...  ..  ..                ...         ...   
1991  1234  1201  1300   66   1  54                 15    0.293483   
1992    19    20   241    2  59   1                 17    0.113590   
1993     4     2    26    0  19   1                 13    0.155844   
1994    13     6    73    1  24   0                 10    0.206731   
1995   757   430   734   74  40  52                 15    0.263467   

      Career SLG  Career OBP  Career OPS    OPS Y1    OPS Y2    OPS Y3  \
0       0.291217    0.235294    0.526511  0.000000  0.219780  0.367510   
1       0.267556    0.285603    0.553158  1.000000  0.560802  0.578379   
2       0.310877    0.269111    0.579987  0.368132  0.219780  0.462535   
3       0.228029    0.237251    0.465279  0.000000  0.550000  0.363387   
4       0.689762    0.473925    1.163687  0.500000  0.952325  0.730611   
...          ...         ...         ...       ...       ...       ...   
1991    0.536897    0.406042    0.942939  0.707851  0.949396  1.050683   
1992    0.166329    0.151163    0.317491  0.235294  0.877143  0.215385   
1993    0.181818    0.175000    0.356818  0.500000  1.333333  0.285714   
1994    0.245192    0.232558    0.477750  1.250000  0.000000  0.000000   
1995    0.417238    0.326621    0.743859  0.760116  0.697935  0.724389   

        OPS Y4    OPS Y5    OPS Y6    OPS Y7    OPS Y8    OPS Y9   OPS Y10  \
0     0.496266  0.379030  0.774655  0.456006  0.692935  0.621154  0.533333   
1     0.470550  0.731898  0.400920  0.559740  0.379742  0.542872  0.634387   
2     0.260180  0.455696  0.519551  0.591622  0.679654  0.537423  0.611333   
3     0.473844  0.475806  0.000000  0.479365  0.464706  0.431818  0.991071   
4     0.856730  0.967903  1.114268  1.379841  1.355617  1.103689  1.313417   
...        ...       ...       ...       ...       ...       ...       ...   
1991  0.982479  0.927351  1.015958  0.934124  1.040773  0.896031  0.986336   
1992  0.370402  0.476190  0.275862  0.450840  0.000000  0.000000  0.000000   
1993  0.833333  0.400000  0.000000  0.000000  0.400000  0.594118  0.000000   
1994  0.571429  0.496781  0.507143  0.378788  0.500000  0.461538  0.400000   
1995  0.647763  0.789018  0.817684  0.772115  0.821899  0.714386  0.714348   

        AVG Y1    AVG Y2    AVG Y3    AVG Y4    AVG Y5    AVG Y6    AVG Y7  \
0     0.000000  0.076923  0.164179  0.190909  0.134146  0.268293  0.165217   
1     0.250000  0.177215  0.216495  0.145631  0.222222  0.126437  0.181818   
2     0.153846  0.076923  0.206522  0.114754  0.215190  0.203883  0.242105   
3     0.000000  0.250000  0.163043  0.190909  0.225806  0.000000  0.174603   
4     0.200000  0.315217  0.268116  0.32520

In [4]:
from_2000_csv = "./data/step4_from_2000.csv"
from_2000 = pd.read_csv(from_2000_csv)
from_2000

ID             Player    PA    AB     R     H   2B  3B   HR  RBI  \
0    pierrju01        Juan Pierre  8280  7525  1073  2217  255  94   18  517   
1     nadyxa01        Xavier Nady  3241  2969   365   797  159   7  104  410   
2    moellch01       Chad Moeller  1539  1392   146   315   74   7   29  132   
3    schnebr01    Brian Schneider  3570  3165   284   781  167   9   67  387   
4    wellski01          Kip Wells   371   331    30    63   10   1    4   17   
..         ...                ...   ...   ...   ...   ...  ...  ..  ...  ...   
398  perezhe01       Hernan Perez  1846  1745   188   436   74  11   45  180   
399  gomesya01          Yan Gomes  3274  3006   369   742  158   8  117  416   
400  simmoan01  Andrelton Simmons  4731  4366   493  1156  200  23   70  437   
401  mercejo03       Jordy Mercer  3416  3104   327   796  173  15   66  308   
402  grandya01    Yasmani Grandal  3861  3233   461   777  152   7  172  505   

      BB   SO  HBP   SH  SF  Number of Seasons  Career AVG  Career SLG  \
0    464  479  102  167  20                 14    0.294618    0.360664   
1    189  626   58    7  18                 12    0.268441    0.431795   
2    108  331   15   16   8                 11    0.226293    0.352011   
3    331  526   22   26  26                 13    0.246761    0.368720   
4      4  143    2   34   0                 11    0.190332    0.262840   
..   ...  ...  ...  ...  ..                ...         ...         ...   
398   76  397    1   12  12                 10    0.249857    0.382235   
399  185  794   50    2  31                 10    0.246840    0.421490   
400  297  448   26   13  29                 10    0.264773    0.369217   
401  246  589   27   22  17                 10    0.256443    0.385631   
402  574  913   20    3  31                 10    0.240334    0.451284   

     Career OBP  Career OPS    OPS Y1    OPS Y2    OPS Y3    OPS Y4    OPS Y5  \
0      0.343114    0.703779  0.673488  0.793087  0.675184  0.733904  0.780886   
1      0.322820    0.754615  2.000000  0.711731  0.716789  0.759777  0.790246   
2      0.287590    0.639602  0.534307  0.627880  0.851913  0.769733  0.568145   
3      0.319977    0.688698  0.563379  0.859248  0.798068  0.702540  0.724134   
4      0.204748    0.467588  0.000000  0.333333  0.460317  0.482310  0.541456   
..          ...         ...       ...       ...       ...       ...       ...   
398    0.279716    0.661951  1.000000  0.444664  0.533333  0.583502  0.730326   
399    0.298594    0.720084  0.630983  0.825949  0.784906  0.658537  0.527451   
400    0.313480    0.682697  0.750827  0.691599  0.617196  0.659624  0.689723   
401    0.314968    0.700599  0.635674  0.771547  0.692806  0.613224  0.701352   
402    0.355365    0.806649  0.862555  0.692761  0.727844  0.755758  0.816092   

       OPS Y6    OPS Y7    OPS Y8    OPS Y9   OPS Y10    AVG Y1    AVG Y2  \
0    0.679930  0.717426  0.684746  0.654683  0.757490  0.310000  0.327391   
1    0.805425  0.867406  0.738916  0.659671  0.646219  1.000000  0.266846   
2    0.623844  0.506279  0.407581  0.640350  0.751334  0.210938  0.232143   
3    0.739263  0.649357  0.661366  0.706638  0.626961  0.234783  0.317073   
4    0.400484  0.181818  0.716981  0.000000  0.181818  0.000000  0.166667   
..        ...       ...       ...       ...       ...       ...       ...   
398  0.703826  0.676495  0.641605  0.333333  0.195489  0.500000  0.196970   
399  0.707728  0.761775  0.704177  0.787218  0.722537  0.204082  0.293515   
400  0.751810  0.754196  0.673284  0.702389  0.557754  0.289157  0.247525   
401  0.732539  0.695653  0.747463  0.472727  0.671493  0.209677  0.285285   
402  0.766596  0.815330  0.847583  0.772876  0.939499  0.296875  0.215909   

       AVG Y3    AVG Y4    AVG Y5    AVG Y6    AVG Y7    AVG Y8    AVG Y9  \
0    0.287162  0.305389  0.325959  0.275915  0.291845  0.293413  0.282667   
1    0.246753  0.260736  0.279915  0.278422  0.304505  0.285714  0.255521   
2    0.285714  0.267782  0.208202

In [18]:
focus_on = ['ID', 'Player', 'PA', 'Number of Seasons', 'Career OPS', 'OPS Y1', 'OPS Y2', 'OPS Y3', 'OPS Y4', 'OPS Y5', 'OPS Y10'] 
pre_2000_ops_focused = pre_2000[focus_on]
pre_2000_ops_focused

ID           Player     PA  Number of Seasons  Career OPS  \
0     willeed01       Ed Willett    704                 10    0.526511   
1     daussho01      Hooks Dauss   1324                 15    0.553158   
2     coopewi01    Wilbur Cooper   1320                 15    0.579987   
3     mamaual01        Al Mamaux    466                 12    0.465279   
4      ruthba01        Babe Ruth  10624                 22    1.163687   
...         ...              ...    ...                ...         ...   
1991  berkmla01    Lance Berkman   7814                 15    0.942939   
1992  burnea.01     A.J. Burnett    575                 17    0.317491   
1993  garcifr03    Freddy Garcia     99                 13    0.356818   
1994  weaveje01      Jeff Weaver    239                 10    0.477750   
1995  hernara02  Ramon Hernandez   5701                 15    0.743859   

        OPS Y1    OPS Y2    OPS Y3    OPS Y4    OPS Y5   OPS Y10  
0     0.000000  0.219780  0.367510  0.496266  0.379030  0.533333  
1     1.000000  0.560802  0.578379  0.470550  0.731898  0.634387  
2     0.368132  0.219780  0.462535  0.260180  0.455696  0.611333  
3     0.000000  0.550000  0.363387  0.473844  0.475806  0.991071  
4     0.500000  0.952325  0.730611  0.856730  0.967903  1.313417  
...        ...       ...       ...       ...       ...       ...  
1991  0.707851  0.949396  1.050683  0.982479  0.927351  0.986336  
1992  0.235294  0.877143  0.215385  0.370402  0.476190  0.000000  
1993  0.500000  1.333333  0.285714  0.833333  0.400000  0.000000  
1994  1.250000  0.000000  0.000000  0.571429  0.496781  0.400000  
1995  0.760116  0.697935  0.724389  0.647763  0.789018  0.714348  

[1996 rows x 11 columns]

In [36]:
ops3 = ['OPS Y1', 'OPS Y2', 'OPS Y3']
X3 = pre_2000_ops_focused[ops3]
X3

OPS Y1    OPS Y2    OPS Y3
0     0.000000  0.219780  0.367510
1     1.000000  0.560802  0.578379
2     0.368132  0.219780  0.462535
3     0.000000  0.550000  0.363387
4     0.500000  0.952325  0.730611
...        ...       ...       ...
1991  0.707851  0.949396  1.050683
1992  0.235294  0.877143  0.215385
1993  0.500000  1.333333  0.285714
1994  1.250000  0.000000  0.000000
1995  0.760116  0.697935  0.724389

[1996 rows x 3 columns]

In [37]:
X3 = X3.values
X3

array([[0.        , 0.21978022, 0.36751027],
       [1.        , 0.56080216, 0.57837942],
       [0.36813187, 0.21978022, 0.46253469],
       ...,
       [0.5       , 1.33333333, 0.28571429],
       [1.25      , 0.        , 0.        ],
       [0.76011615, 0.69793548, 0.72438852]])

OPS5

In [54]:
ops5 = ['OPS Y1', 'OPS Y2', 'OPS Y3', 'OPS Y4', 'OPS Y5']
X5 = pre_2000_ops_focused[ops5]
X5

OPS Y1    OPS Y2    OPS Y3    OPS Y4    OPS Y5
0     0.000000  0.219780  0.367510  0.496266  0.379030
1     1.000000  0.560802  0.578379  0.470550  0.731898
2     0.368132  0.219780  0.462535  0.260180  0.455696
3     0.000000  0.550000  0.363387  0.473844  0.475806
4     0.500000  0.952325  0.730611  0.856730  0.967903
...        ...       ...       ...       ...       ...
1991  0.707851  0.949396  1.050683  0.982479  0.927351
1992  0.235294  0.877143  0.215385  0.370402  0.476190
1993  0.500000  1.333333  0.285714  0.833333  0.400000
1994  1.250000  0.000000  0.000000  0.571429  0.496781
1995  0.760116  0.697935  0.724389  0.647763  0.789018

[1996 rows x 5 columns]

In [55]:
X5 = X5.values
X5

array([[0.        , 0.21978022, 0.36751027, 0.49626623, 0.37903   ],
       [1.        , 0.56080216, 0.57837942, 0.47055016, 0.73189763],
       [0.36813187, 0.21978022, 0.46253469, 0.2601798 , 0.4556962 ],
       ...,
       [0.5       , 1.33333333, 0.28571429, 0.83333333, 0.4       ],
       [1.25      , 0.        , 0.        , 0.57142857, 0.49678068],
       [0.76011615, 0.69793548, 0.72438852, 0.64776292, 0.78901761]])

In [57]:
ops_pred610c = ['OPS Y6', 'OPS Y10', 'Career OPS']
y610c = pre_2000[ops_pred610c]
y610c

OPS Y6   OPS Y10  Career OPS
0     0.774655  0.533333    0.526511
1     0.400920  0.634387    0.553158
2     0.519551  0.611333    0.579987
3     0.000000  0.991071    0.465279
4     1.114268  1.313417    1.163687
...        ...       ...         ...
1991  1.015958  0.986336    0.942939
1992  0.275862  0.000000    0.317491
1993  0.000000  0.000000    0.356818
1994  0.507143  0.400000    0.477750
1995  0.817684  0.714348    0.743859

[1996 rows x 3 columns]

In [58]:
y610c = y610c.values
y610c

array([[0.77465536, 0.53333333, 0.52651137],
       [0.40091954, 0.63438735, 0.55315806],
       [0.51955108, 0.61133342, 0.57998739],
       ...,
       [0.        , 0.        , 0.35681818],
       [0.50714286, 0.4       , 0.47775045],
       [0.817684  , 0.71434791, 0.74385874]])

In [27]:
ops_pred4 = ['OPS Y4']
y4 = pre_2000_ops_focused[ops_pred4]
y4

OPS Y4
0     0.496266
1     0.470550
2     0.260180
3     0.473844
4     0.856730
...        ...
1991  0.982479
1992  0.370402
1993  0.833333
1994  0.571429
1995  0.647763

[1996 rows x 1 columns]

In [35]:
y4 = y4.values
y4

array([[0.49626623],
       [0.47055016],
       [0.2601798 ],
       ...,
       [0.83333333],
       [0.57142857],
       [0.64776292]])

In [48]:
ops_pred4510 = ['OPS Y4', 'OPS Y5', 'OPS Y10']
y4510 = pre_2000_ops_focused[ops_pred4510]
y4510

OPS Y4    OPS Y5   OPS Y10
0     0.496266  0.379030  0.533333
1     0.470550  0.731898  0.634387
2     0.260180  0.455696  0.611333
3     0.473844  0.475806  0.991071
4     0.856730  0.967903  1.313417
...        ...       ...       ...
1991  0.982479  0.927351  0.986336
1992  0.370402  0.476190  0.000000
1993  0.833333  0.400000  0.000000
1994  0.571429  0.496781  0.400000
1995  0.647763  0.789018  0.714348

[1996 rows x 3 columns]

In [49]:
y4510 = y4510.values
y4510

array([[0.49626623, 0.37903   , 0.53333333],
       [0.47055016, 0.73189763, 0.63438735],
       [0.2601798 , 0.4556962 , 0.61133342],
       ...,
       [0.83333333, 0.4       , 0.        ],
       [0.57142857, 0.49678068, 0.4       ],
       [0.64776292, 0.78901761, 0.71434791]])

## For independent test data

In [10]:
from_2000_ops_focused = from_2000[focus_on]
from_2000_ops_focused

ID             Player    PA  Number of Seasons  Career OPS  \
0    pierrju01        Juan Pierre  8280                 14    0.703779   
1     nadyxa01        Xavier Nady  3241                 12    0.754615   
2    moellch01       Chad Moeller  1539                 11    0.639602   
3    schnebr01    Brian Schneider  3570                 13    0.688698   
4    wellski01          Kip Wells   371                 11    0.467588   
..         ...                ...   ...                ...         ...   
398  perezhe01       Hernan Perez  1846                 10    0.661951   
399  gomesya01          Yan Gomes  3274                 10    0.720084   
400  simmoan01  Andrelton Simmons  4731                 10    0.682697   
401  mercejo03       Jordy Mercer  3416                 10    0.700599   
402  grandya01    Yasmani Grandal  3861                 10    0.806649   

       OPS Y1    OPS Y2    OPS Y3    OPS Y4    OPS Y5   OPS Y10  
0    0.673488  0.793087  0.675184  0.733904  0.780886  0.757490  
1    2.000000  0.711731  0.716789  0.759777  0.790246  0.646219  
2    0.534307  0.627880  0.851913  0.769733  0.568145  0.751334  
3    0.563379  0.859248  0.798068  0.702540  0.724134  0.626961  
4    0.000000  0.333333  0.460317  0.482310  0.541456  0.181818  
..        ...       ...       ...       ...       ...       ...  
398  1.000000  0.444664  0.533333  0.583502  0.730326  0.195489  
399  0.630983  0.825949  0.784906  0.658537  0.527451  0.722537  
400  0.750827  0.691599  0.617196  0.659624  0.689723  0.557754  
401  0.635674  0.771547  0.692806  0.613224  0.701352  0.671493  
402  0.862555  0.692761  0.727844  0.755758  0.816092  0.939499  

[403 rows x 11 columns]

In [65]:
from_2000_career = from_2000[['ID', 'Player', 'Career OPS', 'OPS Y1', 'OPS Y2', 'OPS Y3', 'OPS Y4', 'OPS Y5', 'OPS Y6', 'OPS Y10']]
from_2000_career

ID             Player  Career OPS    OPS Y1    OPS Y2    OPS Y3  \
0    pierrju01        Juan Pierre    0.703779  0.673488  0.793087  0.675184   
1     nadyxa01        Xavier Nady    0.754615  2.000000  0.711731  0.716789   
2    moellch01       Chad Moeller    0.639602  0.534307  0.627880  0.851913   
3    schnebr01    Brian Schneider    0.688698  0.563379  0.859248  0.798068   
4    wellski01          Kip Wells    0.467588  0.000000  0.333333  0.460317   
..         ...                ...         ...       ...       ...       ...   
398  perezhe01       Hernan Perez    0.661951  1.000000  0.444664  0.533333   
399  gomesya01          Yan Gomes    0.720084  0.630983  0.825949  0.784906   
400  simmoan01  Andrelton Simmons    0.682697  0.750827  0.691599  0.617196   
401  mercejo03       Jordy Mercer    0.700599  0.635674  0.771547  0.692806   
402  grandya01    Yasmani Grandal    0.806649  0.862555  0.692761  0.727844   

       OPS Y4    OPS Y5    OPS Y6   OPS Y10  
0    0.733904  0.780886  0.679930  0.757490  
1    0.759777  0.790246  0.805425  0.646219  
2    0.769733  0.568145  0.623844  0.751334  
3    0.702540  0.724134  0.739263  0.626961  
4    0.482310  0.541456  0.400484  0.181818  
..        ...       ...       ...       ...  
398  0.583502  0.730326  0.703826  0.195489  
399  0.658537  0.527451  0.707728  0.722537  
400  0.659624  0.689723  0.751810  0.557754  
401  0.613224  0.701352  0.732539  0.671493  
402  0.755758  0.816092  0.766596  0.939499  

[403 rows x 10 columns]

## Models...

#### OPS-3 predicting Y4 OPS

In [43]:
import pandas as pd
import numpy as np


# Print size of the dataset
print("dataset dimensions: {}".format(X3.shape)) 

# Import linear regression and loss (mean_squared_error) from Sklearn package
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error


from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X3, y4, test_size = 0.2, random_state = 42)


# Build a linear regression object
LinReg = LinearRegression()

# Fit a linear regression model
LinReg.fit(X_train, y_train)

y_predict = LinReg.predict(X_test)



# Calculate mean absolute error
from sklearn.metrics import mean_absolute_error
mae = mean_absolute_error(y_test, y_predict)

# Calculate root mean squared error (RMSE)
from sklearn.metrics import mean_squared_error
rmse = (np.sqrt(mean_squared_error(y_test, y_predict)))

# Calculate r--squared
from sklearn.metrics import r2_score
r2 = r2_score(y_test, y_predict)

# calculate adjusted r--squared
k = len(LinReg.coef_)+1
n = len(y_test)
Adjusted_r2 = 1- ((1-r2)*(n-1) / (n-k-1) )

# print intercept and coefficients
print("The intercept of the fitted model is: %.3f" % LinReg.intercept_)
#print("The coefficients of the model are:\n" , [float('{:.3f}'.format(x)) for x in LinReg.coef_ ])

coeffs = []
for x in LinReg.coef_:
    coeffs.append(x)
    
print("The coefficients of the model are:\n", coeffs)


print("The performance of the model")
print("--------------------------------------")
print('MAE is %.3f' % (mae))
print('RMSE is %.3f' % (rmse))
print('R-Squared is %.3f' % (r2))
print('Adjusted R-Squared is %.3f' % (Adjusted_r2))

dataset dimensions: (1996, 3)
The intercept of the fitted model is: 0.190
The coefficients of the model are:
 [array([0.07789985, 0.19743204, 0.46528272])]
The performance of the model
--------------------------------------
MAE is 0.112
RMSE is 0.171
R-Squared is 0.353
Adjusted R-Squared is 0.350


## X and y for OPS-3 using averages

In [45]:
ops3_plus = ['OPS Y1', 'OPS Y2', 'OPS Y3', 'AVG Y1', 'AVG Y2', 'AVG Y3' ]
X3_plus = pre_2000[ops3_plus].values
X3_plus

array([[0.        , 0.21978022, 0.36751027, 0.        , 0.07692308,
        0.1641791 ],
       [1.        , 0.56080216, 0.57837942, 0.25      , 0.17721519,
        0.21649485],
       [0.36813187, 0.21978022, 0.46253469, 0.15384615, 0.07692308,
        0.20652174],
       ...,
       [0.5       , 1.33333333, 0.28571429, 0.25      , 0.66666667,
        0.14285714],
       [1.25      , 0.        , 0.        , 0.5       , 0.        ,
        0.        ],
       [0.76011615, 0.69793548, 0.72438852, 0.27941176, 0.24105012,
        0.25386313]])

In [47]:
import pandas as pd
import numpy as np


# Print size of the dataset
print("dataset dimensions: {}".format(X3_plus.shape)) 

# Import linear regression and loss (mean_squared_error) from Sklearn package
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error


from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X3_plus, y4, test_size = 0.2, random_state = 42)


# Build a linear regression object
LinReg = LinearRegression()

# Fit a linear regression model
LinReg.fit(X_train, y_train)

y_predict = LinReg.predict(X_test)



# Calculate mean absolute error
from sklearn.metrics import mean_absolute_error
mae = mean_absolute_error(y_test, y_predict)

# Calculate root mean squared error (RMSE)
from sklearn.metrics import mean_squared_error
rmse = (np.sqrt(mean_squared_error(y_test, y_predict)))

# Calculate r--squared
from sklearn.metrics import r2_score
r2 = r2_score(y_test, y_predict)

# calculate adjusted r--squared
k = len(LinReg.coef_)+1
n = len(y_test)
Adjusted_r2 = 1- ((1-r2)*(n-1) / (n-k-1) )

# print intercept and coefficients
print("The intercept of the fitted model is: %.3f" % LinReg.intercept_)

coeffs = []
for x in LinReg.coef_:
    coeffs.append(x)
    
print("The coefficients of the model are:\n", coeffs)


print("The performance of the model")
print("--------------------------------------")
print('MAE is %.3f' % (mae))
print('RMSE is %.3f' % (rmse))
print('R-Squared is %.3f' % (r2))
print('Adjusted R-Squared is %.3f' % (Adjusted_r2))

dataset dimensions: (1996, 6)
The intercept of the fitted model is: 0.214
The coefficients of the model are:
 [array([ 0.1034422 ,  0.32288395,  0.77477714, -0.08956074, -0.36750794,
       -0.88150655])]
The performance of the model
--------------------------------------
MAE is 0.110
RMSE is 0.168
R-Squared is 0.372
Adjusted R-Squared is 0.369


In [ ]:
MAE is 0.112
RMSE is 0.171
R-Squared is 0.353
Adjusted R-Squared is 0.350

4510

In [51]:
import pandas as pd
import numpy as np


# Print size of the dataset
print("dataset dimensions: {}".format(X3.shape)) 

# Import linear regression and loss (mean_squared_error) from Sklearn package
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error


from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X3, y4510, test_size = 0.2, random_state = 42)


# Build a linear regression object
LinReg = LinearRegression()

# Fit a linear regression model
LinReg.fit(X_train, y_train)

y_predict = LinReg.predict(X_test)



# Calculate mean absolute error
from sklearn.metrics import mean_absolute_error
mae = mean_absolute_error(y_test, y_predict)

# Calculate root mean squared error (RMSE)
from sklearn.metrics import mean_squared_error
rmse = (np.sqrt(mean_squared_error(y_test, y_predict)))

# Calculate r--squared
from sklearn.metrics import r2_score
r2 = r2_score(y_test, y_predict)

# calculate adjusted r--squared
k = len(LinReg.coef_)+1
n = len(y_test)
Adjusted_r2 = 1- ((1-r2)*(n-1) / (n-k-1) )

# print intercept and coefficients
# print("The intercept of the fitted model is: %.3f" % LinReg.intercept_)

# coeffs = []
# for x in LinReg.coef_:
#     coeffs.append(x)
    
# print("The coefficients of the model are:\n", coeffs)


print("The performance of the model")
print("--------------------------------------")
print('MAE is %.3f' % (mae))
print('RMSE is %.3f' % (rmse))
print('R-Squared is %.3f' % (r2))
print('Adjusted R-Squared is %.3f' % (Adjusted_r2))

dataset dimensions: (1996, 3)
The performance of the model
--------------------------------------
MAE is 0.129
RMSE is 0.190
R-Squared is 0.331
Adjusted R-Squared is 0.324


In [52]:
y_predict

array([[0.55001115, 0.55611356, 0.52584169],
       [0.91824109, 0.91913897, 0.86536026],
       [0.78814808, 0.79998394, 0.77343465],
       ...,
       [0.62978581, 0.62223257, 0.58443999],
       [0.48658673, 0.5008462 , 0.4459767 ],
       [0.72362583, 0.72771215, 0.68345481]])

In [53]:
y_test

array([[0.60148976, 0.44649621, 0.55042735],
       [1.03259288, 1.21675077, 0.88475274],
       [0.7146759 , 0.84023465, 0.72683012],
       ...,
       [0.83630031, 0.80103638, 0.68282828],
       [0.69070513, 0.75149077, 0.80986938],
       [0.76431466, 0.69238805, 0.70809376]])

In [125]:
import pandas as pd
import numpy as np


# Print size of the dataset
print("dataset dimensions: {}".format(X5.shape)) 

# Import linear regression and loss (mean_squared_error) from Sklearn package
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error


from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X5, y610c, test_size = 0.2, random_state = 42)


# Build a linear regression object
LinReg = LinearRegression()

# Fit a linear regression model
LinReg.fit(X_train, y_train)

y_predict = LinReg.predict(X_test)



# Calculate mean absolute error
from sklearn.metrics import mean_absolute_error
mae = mean_absolute_error(y_test, y_predict)

# Calculate root mean squared error (RMSE)
from sklearn.metrics import mean_squared_error
rmse = (np.sqrt(mean_squared_error(y_test, y_predict)))

# Calculate r--squared
from sklearn.metrics import r2_score
r2 = r2_score(y_test, y_predict)

# calculate adjusted r--squared
k = len(LinReg.coef_)+1
n = len(y_test)
Adjusted_r2 = 1- ((1-r2)*(n-1) / (n-k-1) )

# print intercept and coefficients
# print("The intercept of the fitted model is: %.3f" % LinReg.intercept_)

# coeffs = []
# for x in LinReg.coef_:
#     coeffs.append(x)
    
# print("The coefficients of the model are:\n", coeffs)


print("The performance of the model")
print("--------------------------------------")
print('MAE is %.3f' % (mae))
print('RMSE is %.3f' % (rmse))
print('R-Squared is %.3f' % (r2))
print('Adjusted R-Squared is %.3f' % (Adjusted_r2))

dataset dimensions: (1996, 5)
The performance of the model
--------------------------------------
MAE is 0.095
RMSE is 0.154
R-Squared is 0.609
Adjusted R-Squared is 0.605


In [73]:
y_test

array([[0.62600502, 0.55042735, 0.60280427],
       [1.06089582, 0.88475274, 0.97404439],
       [0.85451152, 0.72683012, 0.7945162 ],
       ...,
       [0.8408054 , 0.68282828, 0.77247351],
       [0.7075176 , 0.80986938, 0.71003844],
       [0.80099274, 0.70809376, 0.72399678]])

In [74]:
y_predict

array([[0.53916746, 0.49629127, 0.52371754],
       [1.05086976, 0.99981968, 1.04113919],
       [0.79747239, 0.77263992, 0.79210866],
       ...,
       [0.74714829, 0.69463251, 0.72647821],
       [0.63394459, 0.58222442, 0.62099093],
       [0.73182027, 0.67907525, 0.71835238]])

### Other models...

#### Lasso

In [128]:
import numpy as np
import pandas as pd
from sklearn.linear_model import Ridge, Lasso
from sklearn.metrics import mean_squared_error,r2_score
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn import model_selection
import matplotlib.pyplot as plt
from sklearn.linear_model import RidgeCV, LassoCV


lasso_model = MultiTaskLasso().fit(X_train, y_train)
y_predict = lasso_model.predict(X_test)
y_predict

array([[0.65521054, 0.61294853, 0.64549741],
       [0.65521054, 0.61294853, 0.64549741],
       [0.65521054, 0.61294853, 0.64549741],
       ...,
       [0.65521054, 0.61294853, 0.64549741],
       [0.65521054, 0.61294853, 0.64549741],
       [0.65521054, 0.61294853, 0.64549741]])

In [129]:
# Calculate mean absolute error
from sklearn.metrics import mean_absolute_error
mae = mean_absolute_error(y_test, y_predict)

# Calculate root mean squared error (RMSE)
from sklearn.metrics import mean_squared_error
rmse = (np.sqrt(mean_squared_error(y_test, y_predict)))

# Calculate r--squared
from sklearn.metrics import r2_score
r2 = r2_score(y_test, y_predict)

# calculate adjusted r--squared
k = len(LinReg.coef_)+1
n = len(y_test)
Adjusted_r2 = 1- ((1-r2)*(n-1) / (n-k-1) )

# print intercept and coefficients
# print("The intercept of the fitted model is: %.3f" % LinReg.intercept_)

# coeffs = []
# for x in LinReg.coef_:
#     coeffs.append(x)
    
# print("The coefficients of the model are:\n", coeffs)


print("The performance of the model")
print("--------------------------------------")
print('MAE is %.3f' % (mae))
print('RMSE is %.3f' % (rmse))
print('R-Squared is %.3f' % (r2))
print('Adjusted R-Squared is %.3f' % (Adjusted_r2))

The performance of the model
--------------------------------------
MAE is 0.173
RMSE is 0.228
R-Squared is -0.001
Adjusted R-Squared is -0.011


#### Lasso CV

In [131]:
import pandas as pd
from numpy import arange
from sklearn.linear_model import LassoCV, MultiTaskLasso
from sklearn.model_selection import RepeatedKFold


#define cross-validation method to evaluate model
cv = RepeatedKFold(n_splits=10, n_repeats=3, random_state=1)

#define model
#lassoCV_model = LassoCV(alphas=arange(0, 1, 0.01), cv=cv, n_jobs=-1)

# lassoCV_model = LassoCV().fit(X_train, y_train)
# lassoCV_model.predict(X_test)


lassoCV_model = MultiTaskLassoCV(cv=5).fit(X_train, y_train)
y_predict = lassoCV_model.predict(X_test)
y_predict

#fit model
#lassoCV_model.fit(X_train, y_train)

#display lambda that produced the lowest test MSE
#print(model.alpha_)


array([[0.54239611, 0.49943446, 0.52799784],
       [1.04162441, 0.99008904, 1.03150018],
       [0.79477649, 0.76562414, 0.7886231 ],
       ...,
       [0.7461746 , 0.69418566, 0.72728205],
       [0.63508948, 0.58612432, 0.6227826 ],
       [0.72964348, 0.67782658, 0.71662991]])

In [132]:
# Calculate mean absolute error
from sklearn.metrics import mean_absolute_error
mae = mean_absolute_error(y_test, y_predict)

# Calculate root mean squared error (RMSE)
from sklearn.metrics import mean_squared_error
rmse = (np.sqrt(mean_squared_error(y_test, y_predict)))

# Calculate r--squared
from sklearn.metrics import r2_score
r2 = r2_score(y_test, y_predict)

# calculate adjusted r--squared
k = len(LinReg.coef_)+1
n = len(y_test)
Adjusted_r2 = 1- ((1-r2)*(n-1) / (n-k-1) )

# print intercept and coefficients
# print("The intercept of the fitted model is: %.3f" % LinReg.intercept_)

# coeffs = []
# for x in LinReg.coef_:
#     coeffs.append(x)
    
# print("The coefficients of the model are:\n", coeffs)


print("The performance of the model")
print("--------------------------------------")
print('MAE is %.3f' % (mae))
print('RMSE is %.3f' % (rmse))
print('R-Squared is %.3f' % (r2))
print('Adjusted R-Squared is %.3f' % (Adjusted_r2))

The performance of the model
--------------------------------------
MAE is 0.095
RMSE is 0.154
R-Squared is 0.606
Adjusted R-Squared is 0.602


#### Gradient Regressor Booster

In [133]:
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.multioutput import MultiOutputRegressor

params = {'n_estimators': 5000, 'max_depth': 4, 'min_samples_split': 2, 'min_samples_leaf': 2
         }

#GRB_model = GradientBoostingRegressor().fit(X_train, y_train)
#GRB_model.predict(X_test)

GRB_model = MultiOutputRegressor(GradientBoostingRegressor(**params)).fit(X_train, y_train)
y_predict = GRB_model.predict(X_test)
y_predict

array([[0.32188426, 0.3208446 , 0.49595284],
       [0.99407542, 0.83741187, 0.93924969],
       [0.80334533, 0.60955123, 0.83428604],
       ...,
       [0.83192607, 0.74402665, 0.80074322],
       [0.76936533, 0.60323896, 0.68370578],
       [0.73905406, 0.73365576, 0.7132922 ]])

In [111]:
# Calculate mean absolute error
from sklearn.metrics import mean_absolute_error
mae = mean_absolute_error(y_test, y_predict)

# Calculate root mean squared error (RMSE)
from sklearn.metrics import mean_squared_error
rmse = (np.sqrt(mean_squared_error(y_test, y_predict)))

# Calculate r--squared
from sklearn.metrics import r2_score
r2 = r2_score(y_test, y_predict)

# calculate adjusted r--squared
k = len(LinReg.coef_)+1
n = len(y_test)
Adjusted_r2 = 1- ((1-r2)*(n-1) / (n-k-1) )

# print intercept and coefficients
# print("The intercept of the fitted model is: %.3f" % LinReg.intercept_)

# coeffs = []
# for x in LinReg.coef_:
#     coeffs.append(x)
    
# print("The coefficients of the model are:\n", coeffs)


print("The performance of the model")
print("--------------------------------------")
print('MAE is %.3f' % (mae))
print('RMSE is %.3f' % (rmse))
print('R-Squared is %.3f' % (r2))
print('Adjusted R-Squared is %.3f' % (Adjusted_r2))

The performance of the model
--------------------------------------
MAE is 0.111
RMSE is 0.179
R-Squared is 0.474
Adjusted R-Squared is 0.469


#### Ridge???

In [108]:
ridge_model = Ridge().fit(X_train,y_train)
y_predict = ridge_model.predict(X_test)
y_predict

array([[0.53965435, 0.49701255, 0.52430229],
       [1.04844899, 0.99720985, 1.03867614],
       [0.79690762, 0.77170665, 0.7914351 ],
       ...,
       [0.74549318, 0.6932331 , 0.7249776 ],
       [0.63291635, 0.58123379, 0.61999932],
       [0.73160284, 0.67906256, 0.7182038 ]])

In [107]:
y_test

array([[0.62600502, 0.55042735, 0.60280427],
       [1.06089582, 0.88475274, 0.97404439],
       [0.85451152, 0.72683012, 0.7945162 ],
       ...,
       [0.8408054 , 0.68282828, 0.77247351],
       [0.7075176 , 0.80986938, 0.71003844],
       [0.80099274, 0.70809376, 0.72399678]])

In [109]:
# Calculate mean absolute error
from sklearn.metrics import mean_absolute_error
mae = mean_absolute_error(y_test, y_predict)

# Calculate root mean squared error (RMSE)
from sklearn.metrics import mean_squared_error
rmse = (np.sqrt(mean_squared_error(y_test, y_predict)))

# Calculate r--squared
from sklearn.metrics import r2_score
r2 = r2_score(y_test, y_predict)

# calculate adjusted r--squared
k = len(LinReg.coef_)+1
n = len(y_test)
Adjusted_r2 = 1- ((1-r2)*(n-1) / (n-k-1) )

# print intercept and coefficients
# print("The intercept of the fitted model is: %.3f" % LinReg.intercept_)

# coeffs = []
# for x in LinReg.coef_:
#     coeffs.append(x)
    
# print("The coefficients of the model are:\n", coeffs)


print("The performance of the model")
print("--------------------------------------")
print('MAE is %.3f' % (mae))
print('RMSE is %.3f' % (rmse))
print('R-Squared is %.3f' % (r2))
print('Adjusted R-Squared is %.3f' % (Adjusted_r2))

The performance of the model
--------------------------------------
MAE is 0.095
RMSE is 0.154
R-Squared is 0.608
Adjusted R-Squared is 0.604


### My Test with My Data....

In [67]:
y_my_test = from_2000_career[['OPS Y6', 'OPS Y10', 'Career OPS']]
y_my_test

OPS Y6   OPS Y10  Career OPS
0    0.679930  0.757490    0.703779
1    0.805425  0.646219    0.754615
2    0.623844  0.751334    0.639602
3    0.739263  0.626961    0.688698
4    0.400484  0.181818    0.467588
..        ...       ...         ...
398  0.703826  0.195489    0.661951
399  0.707728  0.722537    0.720084
400  0.751810  0.557754    0.682697
401  0.732539  0.671493    0.700599
402  0.766596  0.939499    0.806649

[403 rows x 3 columns]

In [68]:
X_my_test = from_2000_career[['OPS Y1', 'OPS Y2', 'OPS Y3', 'OPS Y4', 'OPS Y5']]
X_my_test

OPS Y1    OPS Y2    OPS Y3    OPS Y4    OPS Y5
0    0.673488  0.793087  0.675184  0.733904  0.780886
1    2.000000  0.711731  0.716789  0.759777  0.790246
2    0.534307  0.627880  0.851913  0.769733  0.568145
3    0.563379  0.859248  0.798068  0.702540  0.724134
4    0.000000  0.333333  0.460317  0.482310  0.541456
..        ...       ...       ...       ...       ...
398  1.000000  0.444664  0.533333  0.583502  0.730326
399  0.630983  0.825949  0.784906  0.658537  0.527451
400  0.750827  0.691599  0.617196  0.659624  0.689723
401  0.635674  0.771547  0.692806  0.613224  0.701352
402  0.862555  0.692761  0.727844  0.755758  0.816092

[403 rows x 5 columns]

In [69]:
names_my_test = from_2000_career[['Player']]
names_my_test

Player
0          Juan Pierre
1          Xavier Nady
2         Chad Moeller
3      Brian Schneider
4            Kip Wells
..                 ...
398       Hernan Perez
399          Yan Gomes
400  Andrelton Simmons
401       Jordy Mercer
402    Yasmani Grandal

[403 rows x 1 columns]

In [71]:
predict_my_test = LinReg.predict(X_my_test.values)
predict_my_test

#clf_1.predict(X_2000_1.values)

array([[0.74853947, 0.709993  , 0.74135528],
       [0.80075901, 0.73296567, 0.7975965 ],
       [0.70353236, 0.64036737, 0.68679369],
       ...,
       [0.68394867, 0.64296373, 0.6769241 ],
       [0.69844642, 0.65407574, 0.68902122],
       [0.77467623, 0.72549378, 0.76539678]])

In [72]:
y_my_test

OPS Y6   OPS Y10  Career OPS
0    0.679930  0.757490    0.703779
1    0.805425  0.646219    0.754615
2    0.623844  0.751334    0.639602
3    0.739263  0.626961    0.688698
4    0.400484  0.181818    0.467588
..        ...       ...         ...
398  0.703826  0.195489    0.661951
399  0.707728  0.722537    0.720084
400  0.751810  0.557754    0.682697
401  0.732539  0.671493    0.700599
402  0.766596  0.939499    0.806649

[403 rows x 3 columns]